/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Native audio capture using WASAPI (Windows) via cpal.
 * Drop-in replacement for the ffmpeg-based AudioCapture in audio.ts.
 *
 * Audio format: PCM S16LE, 16 kHz, mono — matching Deepgram's expected input.
 */
export declare class AudioCapture {
  constructor(deviceName?: string | undefined | null)
  /** List available audio input devices. */
  static getAvailableDevices(): Array<string>
  /**
   * Start capturing audio from the selected device.
   * Resolves once audio is flowing.
   */
  start(): object
  /** Stop capturing and release the device. */
  stop(): void
  /** Start and keep alive (pre-warm). Same as start() but idempotent. */
  startPersistent(): object
  /** Whether the capture stream is currently active. */
  isRunning(): boolean
  /** Current audio level (0.0–1.0), smoothed via exponential moving average. */
  getAudioLevel(): number
  /** Enable streaming mode. Returns raw PCM chunks via the provided callback. */
  enableStreaming(callback: (err: null, chunk: Buffer) => void): void
  /** Disable streaming mode. */
  disableStreaming(): void
  /** Start buffering audio chunks in memory. */
  startBuffering(): void
  /** Stop buffering and return the accumulated PCM data. */
  stopBuffering(): Buffer | null
  /** Get current buffered audio without stopping. */
  getBufferedAudio(): Buffer | null
}
